/**
 * Error constants
 * Centralized error codes, messages, and types
 */

// ===== ERROR CODES =====
export const ERROR_CODES = {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE',
  VALIDATION_DUPLICATE_VALUE: 'VALIDATION_DUPLICATE_VALUE',

  // Database
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  DATABASE_QUERY_FAILED: 'DATABASE_QUERY_FAILED',
  DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_RECORD_NOT_FOUND: 'DATABASE_RECORD_NOT_FOUND',
  DATABASE_DUPLICATE_ENTRY: 'DATABASE_DUPLICATE_ENTRY',
  DATABASE_FOREIGN_KEY_VIOLATION: 'DATABASE_FOREIGN_KEY_VIOLATION',

  // File Operations
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',

  // External Services
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_INVALID_RESPONSE: 'EXTERNAL_SERVICE_INVALID_RESPONSE',
  EMAIL_SERVICE_FAILED: 'EMAIL_SERVICE_FAILED',
  SMS_SERVICE_FAILED: 'SMS_SERVICE_FAILED',

  // Business Logic
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE'
} as const;

// ===== ERROR MESSAGES =====
export const ERROR_MESSAGES = {
  // Authentication & Authorization
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Invalid token',
  [ERROR_CODES.AUTH_TOKEN_MISSING]: 'Authentication token is required',
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: 'Account is locked due to multiple failed login attempts',
  [ERROR_CODES.AUTH_ACCOUNT_SUSPENDED]: 'Account is suspended',
  [ERROR_CODES.AUTH_EMAIL_NOT_VERIFIED]: 'Email address is not verified',
  [ERROR_CODES.AUTH_2FA_REQUIRED]: 'Two-factor authentication is required',
  [ERROR_CODES.AUTH_2FA_INVALID]: 'Invalid two-factor authentication code',

  // Validation
  [ERROR_CODES.VALIDATION_FAILED]: 'Validation failed',
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 'Required field is missing',
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 'Invalid format',
  [ERROR_CODES.VALIDATION_OUT_OF_RANGE]: 'Value is out of allowed range',
  [ERROR_CODES.VALIDATION_DUPLICATE_VALUE]: 'Value already exists',

  // Database
  [ERROR_CODES.DATABASE_CONNECTION_FAILED]: 'Database connection failed',
  [ERROR_CODES.DATABASE_QUERY_FAILED]: 'Database query failed',
  [ERROR_CODES.DATABASE_CONSTRAINT_VIOLATION]: 'Database constraint violation',
  [ERROR_CODES.DATABASE_RECORD_NOT_FOUND]: 'Record not found',
  [ERROR_CODES.DATABASE_DUPLICATE_ENTRY]: 'Duplicate entry',
  [ERROR_CODES.DATABASE_FOREIGN_KEY_VIOLATION]: 'Foreign key constraint violation',

  // File Operations
  [ERROR_CODES.FILE_UPLOAD_FAILED]: 'File upload failed',
  [ERROR_CODES.FILE_SIZE_EXCEEDED]: 'File size exceeds maximum allowed size',
  [ERROR_CODES.FILE_TYPE_NOT_ALLOWED]: 'File type is not allowed',
  [ERROR_CODES.FILE_NOT_FOUND]: 'File not found',
  [ERROR_CODES.FILE_DELETE_FAILED]: 'File deletion failed',

  // External Services
  [ERROR_CODES.EXTERNAL_SERVICE_UNAVAILABLE]: 'External service is unavailable',
  [ERROR_CODES.EXTERNAL_SERVICE_TIMEOUT]: 'External service timeout',
  [ERROR_CODES.EXTERNAL_SERVICE_INVALID_RESPONSE]: 'Invalid response from external service',
  [ERROR_CODES.EMAIL_SERVICE_FAILED]: 'Email service failed',
  [ERROR_CODES.SMS_SERVICE_FAILED]: 'SMS service failed',

  // Business Logic
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists',
  [ERROR_CODES.COURSE_NOT_FOUND]: 'Course not found',
  [ERROR_CODES.ENROLLMENT_NOT_FOUND]: 'Enrollment not found',
  [ERROR_CODES.PAYMENT_FAILED]: 'Payment failed',
  [ERROR_CODES.QUOTA_EXCEEDED]: 'Quota exceeded',

  // System
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.MAINTENANCE_MODE]: 'Service is under maintenance'
} as const;

// ===== ERROR TYPES =====
export const ERROR_TYPES = {
  AUTHENTICATION: 'AUTHENTICATION',
  AUTHORIZATION: 'AUTHORIZATION',
  VALIDATION: 'VALIDATION',
  DATABASE: 'DATABASE',
  FILE: 'FILE',
  EXTERNAL_SERVICE: 'EXTERNAL_SERVICE',
  BUSINESS_LOGIC: 'BUSINESS_LOGIC',
  SYSTEM: 'SYSTEM'
} as const;

// ===== HTTP STATUS CODES =====
export const HTTP_STATUS_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  BAD_GATEWAY: 502,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
} as const;

// ===== ERROR SEVERITY LEVELS =====
export const ERROR_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
} as const;

// ===== TYPE DEFINITIONS =====
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
export type ErrorMessage = typeof ERROR_MESSAGES[keyof typeof ERROR_MESSAGES];
export type ErrorType = typeof ERROR_TYPES[keyof typeof ERROR_TYPES];
export type HttpStatusCode = typeof HTTP_STATUS_CODES[keyof typeof HTTP_STATUS_CODES];
export type ErrorSeverity = typeof ERROR_SEVERITY[keyof typeof ERROR_SEVERITY];

