--
-- PostgreSQL database dump
--

\restrict arQtM2SBmwHrU8QBNwMVMURXzEO1nnAnrIvKTQYLdPeHaoc5l50l7A1ahyWdLZg

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: lms_user
--

INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000004', 'instructor2@example.com', 'instructor2', '$2b$12$PlUIvWpPRQwKtmNTBrnaYuZPNhC7MDQlfKsVv2rWDq/3cY0xFANwi', 'Jane', 'Smith', '+84901000004', 'Full-stack developer and educator. Passionate about teaching modern JavaScript frameworks.', NULL, 'instructor', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.524+07', '2025-11-03 02:56:57.524+07', NULL, NULL, NULL, NULL, NULL, NULL, 'INS002', 'Computer Science', 'Full-Stack Development, JavaScript', 8, 'master', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000005', 'instructor3@example.com', 'instructor3', '$2b$12$E4vl.GbHBMVKroXRAn4NnuSxSYVlubK9DsUTgG5MgVkouSQXW5YXm', 'Mike', 'Johnson', '+84901000005', 'Data scientist and machine learning expert with Ph.D. in Computer Science.', NULL, 'instructor', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.525+07', '2025-11-03 02:56:57.525+07', NULL, NULL, NULL, NULL, NULL, NULL, 'INS003', 'Computer Science', 'Machine Learning, Data Science, AI', 12, 'phd', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000001', 'superadmin@example.com', 'superadmin', '$2b$12$E7F2ajMXVrv8bemKoBVLqOp3Ey7.4W.SQuKBWmcfCMCyPZQgEY4rS', 'Super', 'Admin', '+84901000001', 'System Super Administrator', NULL, 'admin', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.506+07', '2025-11-03 10:23:10.514+07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000008', 'student3@example.com', 'student3', '$2b$12$WEQjgulKyMyOiLkgiZO7uODROiCJnVgooLireeaxsYZtY81tzRMuO', 'Carol', 'Davis', '+84901000008', 'Frontend developer learning advanced React patterns.', NULL, 'student', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.53+07', '2025-11-03 02:56:57.53+07', NULL, 'STU2024003', 'CNTT-K19', 'Computer Science', 2024, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000009', 'student4@example.com', 'student4', '$2b$12$EcEf77il/vnwGmfac9pVI.UNsPYIwSECEYOvyDePZdQIgJb6Sg5Jy', 'David', 'Miller', '+84901000009', 'Backend developer learning Node.js and databases.', NULL, 'student', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.532+07', '2025-11-03 02:56:57.532+07', NULL, 'STU2024004', 'CNTT-K19', 'Computer Science', 2024, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000010', 'student5@example.com', 'student5', '$2b$12$ZUZLJ87S5zhrM955CQ7GaOrWKf6ZK.SBLSYwEu.e2p232i5EYzscu', 'Eva', 'Garcia', '+84901000010', 'Mobile developer learning React Native.', NULL, 'student', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.534+07', '2025-11-03 02:56:57.534+07', NULL, 'STU2024005', 'CNTT-K19', 'Computer Science', 2024, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000012', 'suspended@example.com', 'suspended', '$2b$12$2J25hPPuGMe8cZSXz1fyw.acTxL9gVXXs2CZfB8ZMQ4fsLtrO4bZq', 'Suspended', 'User', NULL, NULL, NULL, 'student', 'suspended', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.537+07', '2025-11-03 02:56:57.537+07', NULL, 'STU2024012', 'CNTT-K19', 'Computer Science', 2024, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('20000000-0000-0000-0000-000000000011', 'student11@example.com', 'student11', '$2b$12$IlNMm639EEo9n1hyloL2JeSAhAh96u1jW6oChs8yhGAuD9r4xX0nu', 'Student', 'Eleven', NULL, NULL, NULL, 'student', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 10:16:50.332+07', '2025-11-03 10:23:11.038+07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('20000000-0000-0000-0000-000000000021', 'instructor@example.com', 'instructor', '$2b$12$6x3zap1PEpWxTLT7MUeM9uegi/gqqzkIvORf8I8pQ.HNZz00ghNz6', 'John', 'Instructor', NULL, NULL, NULL, 'instructor', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 10:16:50.599+07', '2025-11-03 10:23:11.288+07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000003', 'instructor1@example.com', 'instructor1', '$2b$12$AGnLcMEhkUl5ah9Wg92TTukKF/6c32ZZdkaxRUYWoUDGcVc7hluUy', 'John', 'Doe', NULL, NULL, NULL, 'instructor', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 23:42:44.97817+07', '2025-11-03 23:42:44.97817+07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000002', 'admin@example.com', 'admin', '$2b$12$R3NpC320blNzOp5Gzx9Aze1rueAZ24fu9FXRAY9vTpGazmrZJxkkK', 'System', 'Admin', NULL, NULL, NULL, 'admin', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, '2025-11-04 04:40:38.174+07', 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 23:42:46.063695+07', '2025-11-04 04:40:38.174+07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000007', 'student2@example.com', 'student2', '$2b$12$R3NpC320blNzOp5Gzx9Aze1rueAZ24fu9FXRAY9vTpGazmrZJxkkK', 'Bob', 'Wilson', '+84901000007', 'Computer science student interested in AI and machine learning.', NULL, 'student', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, '2025-11-04 13:38:06.329+07', 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.529+07', '2025-11-04 13:38:06.329+07', NULL, 'STU2024002', 'CNTT-K19', 'Computer Science', 2024, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000011', 'pending@example.com', 'pending', '$2b$12$r5hDGrV/mbj6K/xGvMd5/.C7WFB2KbpaD60GUdzwNVv7rli0t.Lwm', 'Pending', 'User', NULL, NULL, NULL, 'student', 'pending', true, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 02:56:57.536+07', '2025-11-03 02:56:57.536+07', NULL, 'STU2024011', 'CNTT-K19', 'Computer Science', 2024, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, email, username, password, first_name, last_name, phone, bio, avatar, role, status, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, two_factor_enabled, two_factor_secret, two_factor_backup_codes, last_login, login_attempts, lockout_until, token_version, social_id, social_provider, preferences, metadata, created_at, updated_at, email_verified_at, student_id, class, major, year, gpa, instructor_id, department, specialization, experience_years, education_level, research_interests, date_of_birth, gender, address, emergency_contact, emergency_phone) VALUES ('00000000-0000-0000-0000-000000000006', 'student1@example.com', 'student1', '$2b$12$WfR59yTtyXEW74PQB9yjtOG3UDN1UsSijS/y5bk98/jLIGf7pKjrO', 'Alice', 'Brown', NULL, NULL, NULL, 'student', 'active', true, NULL, NULL, NULL, NULL, false, NULL, NULL, '2025-11-04 14:00:55.827+07', 0, NULL, 1, NULL, NULL, NULL, NULL, '2025-11-03 23:42:45.525774+07', '2025-11-04 14:00:55.828+07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--
-- PostgreSQL database dump complete
--

\unrestrict arQtM2SBmwHrU8QBNwMVMURXzEO1nnAnrIvKTQYLdPeHaoc5l50l7A1ahyWdLZg

