/**
 * AI Summary Panel Component
 * Shows AI-generated summary for students
 */

import React, { useMemo, useState } from 'react';
import { marked } from 'marked';
import { useAIAnalysis } from '../../hooks/useAIAnalysis';
import { 
  Sparkles, 
  Clock,
  ChevronDown,
  ChevronUp,
  Lightbulb,
  GraduationCap,
  BookOpen
} from 'lucide-react';

interface AISummaryPanelProps {
  lessonId: string;
}

const renderMarkdownToHtml = (raw?: string | null): string => {
  const trimmed = (raw || '').trim();
  if (!trimmed) return '';
  let html = marked.parse(trimmed, { breaks: true, gfm: true });
  // Loại bỏ các tag lạ mà AI có thể sinh ra (ví dụ </tên_gói>)
  html = (html as string).replace(/<\/?tên_gói>/gi, '');
  return html as string;
};

export const AISummaryPanel: React.FC<AISummaryPanelProps> = ({ lessonId }) => {
  const { analysis, queueStatus } = useAIAnalysis(lessonId);
  const [isExpanded, setIsExpanded] = useState(true);

  // Chuẩn hóa HTML summary ngay sau khi lấy data để đảm bảo hook order luôn cố định
  const summaryHtml = useMemo(
    () => (analysis && analysis.summary ? renderMarkdownToHtml(analysis.summary) : ''),
    [analysis]
  );

  // Check if analysis is in progress
  const isProcessing = queueStatus.some(
    task => task.status === 'pending' || task.status === 'processing'
  );

  // No analysis available
  if (!analysis && !isProcessing) {
    return (
      <div className="bg-gray-50 rounded-lg p-4 text-center text-gray-500">
        <Sparkles className="h-8 w-8 mx-auto mb-2 text-gray-400" />
        <p className="text-sm">No AI summary available yet</p>
      </div>
    );
  }

  // Analysis in progress
  if (isProcessing || (analysis && analysis.status === 'processing')) {
    return (
      <div className="bg-yellow-50 rounded-lg p-4 text-center">
        <Clock className="h-8 w-8 mx-auto mb-2 text-yellow-600 animate-pulse" />
        <p className="text-sm font-medium text-yellow-700">
          AI is analyzing this lesson...
        </p>
        <p className="text-xs text-yellow-600 mt-1">
          This may take a few minutes
        </p>
      </div>
    );
  }

  // Analysis failed
  if (analysis && analysis.status === 'failed') {
    return (
      <div className="bg-red-50 rounded-lg p-4 text-center text-red-700">
        <p className="text-sm font-medium">Failed to generate summary</p>
        <p className="text-xs mt-1">Please contact your instructor</p>
      </div>
    );
  }

  // Analysis completed
  if (analysis && analysis.status === 'completed') {
    return (
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
        {/* Header */}
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="w-full flex items-center justify-between p-4 hover:bg-gray-50 transition-colors"
        >
          <div className="flex items-center space-x-3">
            <Sparkles className="h-6 w-6 text-indigo-600" />
            <div className="text-left">
              <h3 className="text-lg font-semibold text-gray-900">
                AI Summary
              </h3>
              <p className="text-xs text-gray-500">
                Generated by AI • Click to {isExpanded ? 'collapse' : 'expand'}
              </p>
            </div>
          </div>
          {isExpanded ? (
            <ChevronUp className="h-5 w-5 text-gray-400" />
          ) : (
            <ChevronDown className="h-5 w-5 text-gray-400" />
          )}
        </button>

        {/* Content */}
        {isExpanded && (
          <div className="p-4 pt-0 space-y-4">
            {/* Summary */}
            {summaryHtml && (
              <div>
                <h4 className="text-sm font-semibold text-gray-900 mb-2 flex items-center">
                  <BookOpen className="h-4 w-4 mr-1.5 text-indigo-600" />
                  Summary
                </h4>
                <div
                  className="prose prose-sm max-w-none text-gray-700 leading-relaxed [&>p]:mb-2"
                  dangerouslySetInnerHTML={{ __html: summaryHtml }}
                />
              </div>
            )}

            {/* Key Concepts */}
            {analysis.content_key_concepts && analysis.content_key_concepts.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold text-gray-900 mb-2 flex items-center">
                  <Lightbulb className="h-4 w-4 mr-1.5 text-yellow-600" />
                  Key Concepts
                </h4>
                <ul className="space-y-1">
                  {analysis.content_key_concepts.map((concept, index) => (
                    <li key={index} className="flex items-start text-sm text-gray-700">
                      <span className="text-indigo-600 mr-2">•</span>
                      <span>{concept}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Video Key Points */}
            {analysis.video_key_points && analysis.video_key_points.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold text-gray-900 mb-2 flex items-center">
                  <Sparkles className="h-4 w-4 mr-1.5 text-purple-600" />
                  Video Highlights
                </h4>
                <ul className="space-y-1">
                  {analysis.video_key_points.map((point, index) => (
                    <li key={index} className="flex items-start text-sm text-gray-700">
                      <span className="text-purple-600 mr-2">▶</span>
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Learning Objectives */}
            {analysis.learning_objectives && analysis.learning_objectives.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold text-gray-900 mb-2 flex items-center">
                  <GraduationCap className="h-4 w-4 mr-1.5 text-green-600" />
                  Learning Objectives
                </h4>
                <ul className="space-y-1">
                  {analysis.learning_objectives.map((objective, index) => (
                    <li key={index} className="flex items-start text-sm text-gray-700">
                      <span className="text-green-600 mr-2">✓</span>
                      <span>{objective}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Meta Information */}
            <div className="pt-3 border-t border-gray-200 flex flex-wrap gap-4 text-xs text-gray-500">
              {analysis.difficulty_level && (
                <div className="flex items-center">
                  <span className="font-medium mr-1">Difficulty:</span>
                  <span className="capitalize">{analysis.difficulty_level}</span>
                </div>
              )}
              {analysis.estimated_study_time_minutes && (
                <div className="flex items-center">
                  <Clock className="h-4 w-4 mr-1" />
                  <span>~{analysis.estimated_study_time_minutes} min</span>
                </div>
              )}
              {analysis.prerequisites && analysis.prerequisites.length > 0 && (
                <div className="flex items-center">
                  <span className="font-medium mr-1">Prerequisites:</span>
                  <span>{analysis.prerequisites.join(', ')}</span>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    );
  }

  return null;
};
