/**
 * Seeder 001: Seed users
 */

import { Sequelize, QueryTypes } from 'sequelize';
import { hashUtils } from '../utils/hash.util';

export async function seedUsers(sequelize: Sequelize): Promise<void> {
  const users = [
    // Super Admin
    {
      id: '00000000-0000-0000-0000-000000000001',
      email: 'superadmin@example.com',
      username: 'superadmin',
      password: await hashUtils.password.hashPassword('SuperAdmin123!'),
      first_name: 'Super',
      last_name: 'Admin',
      bio: 'System administrator',
      role: 'super_admin',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: null,
      class: null,
      major: null,
      year: null,
      gpa: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    // Admin
    {
      id: '00000000-0000-0000-0000-000000000002',
      email: 'admin@example.com',
      username: 'admin',
      password: await hashUtils.password.hashPassword('Admin123!'),
      first_name: 'System',
      last_name: 'Admin',
      bio: 'System administrator',
      role: 'admin',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: null,
      class: null,
      major: null,
      year: null,
      gpa: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    // Instructors
    {
      id: '00000000-0000-0000-0000-000000000003',
      email: 'instructor1@example.com',
      username: 'GV001',
      password: await hashUtils.password.hashPassword('Instructor123!'),
      first_name: 'John',
      last_name: 'Doe',
      bio: 'Experienced software engineer with 10+ years in web development',
      role: 'instructor',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: 'GV001',
      department: 'Khoa Công nghệ thông tin',
      specialization: 'Lập trình web',
      experience_years: 10,
      education_level: 'master',
      student_id: null,
      class: null,
      major: null,
      year: null,
      gpa: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '00000000-0000-0000-0000-000000000004',
      email: 'instructor2@example.com',
      username: 'GV002',
      password: await hashUtils.password.hashPassword('Instructor123!'),
      first_name: 'Jane',
      last_name: 'Smith',
      bio: 'Full-stack developer specializing in React and Node.js',
      role: 'instructor',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: 'GV002',
      department: 'Khoa Công nghệ thông tin',
      specialization: 'React và Node.js',
      experience_years: 8,
      education_level: 'phd',
      student_id: null,
      class: null,
      major: null,
      year: null,
      gpa: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '00000000-0000-0000-0000-000000000005',
      email: 'instructor3@example.com',
      username: 'GV003',
      password: await hashUtils.password.hashPassword('Instructor123!'),
      first_name: 'Mike',
      last_name: 'Johnson',
      bio: 'Data scientist and machine learning expert',
      role: 'instructor',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: 'GV003',
      department: 'Khoa Công nghệ thông tin',
      specialization: 'Machine Learning và AI',
      experience_years: 12,
      education_level: 'professor',
      student_id: null,
      class: null,
      major: null,
      year: null,
      gpa: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    // Students
    {
      id: '00000000-0000-0000-0000-000000000006',
      email: 'student1@example.com',
      username: '2021001234',
      password: await hashUtils.password.hashPassword('Student123!'),
      first_name: 'Alice',
      last_name: 'Brown',
      bio: 'Aspiring web developer learning React and Node.js',
      role: 'student',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: '2021001234',
      class: 'CNTT-K62',
      major: 'Công nghệ thông tin',
      year: 2021,
      gpa: 3.5,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '00000000-0000-0000-0000-000000000007',
      email: 'student2@example.com',
      username: '2021001235',
      password: await hashUtils.password.hashPassword('Student123!'),
      first_name: 'Bob',
      last_name: 'Wilson',
      bio: 'Computer science student interested in AI and machine learning',
      role: 'student',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: '2021001235',
      class: 'CNTT-K62',
      major: 'Công nghệ thông tin',
      year: 2021,
      gpa: 3.8,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '00000000-0000-0000-0000-000000000008',
      email: 'student3@example.com',
      username: '2022001234',
      password: await hashUtils.password.hashPassword('Student123!'),
      first_name: 'Carol',
      last_name: 'Davis',
      bio: 'Frontend developer learning advanced React patterns',
      role: 'student',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: '2022001234',
      class: 'CNTT-K63',
      major: 'Công nghệ thông tin',
      year: 2022,
      gpa: 3.2,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '00000000-0000-0000-0000-000000000009',
      email: 'student4@example.com',
      username: '2022001235',
      password: await hashUtils.password.hashPassword('Student123!'),
      first_name: 'David',
      last_name: 'Miller',
      bio: 'Backend developer learning Node.js and databases',
      role: 'student',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: '2022001235',
      class: 'CNTT-K63',
      major: 'Công nghệ thông tin',
      year: 2022,
      gpa: 3.6,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '00000000-0000-0000-0000-000000000010',
      email: 'student5@example.com',
      username: '2023001234',
      password: await hashUtils.password.hashPassword('Student123!'),
      first_name: 'Eva',
      last_name: 'Garcia',
      bio: 'Mobile developer learning React Native',
      role: 'student',
      status: 'active',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: '2023001234',
      class: 'CNTT-K64',
      major: 'Công nghệ thông tin',
      year: 2023,
      gpa: 3.4,
      created_at: new Date(),
      updated_at: new Date()
    },
    // Pending verification
    {
      id: '00000000-0000-0000-0000-000000000011',
      email: 'pending@example.com',
      username: 'pending',
      password: await hashUtils.password.hashPassword('Pending123!'),
      first_name: 'Pending',
      last_name: 'User',
      bio: 'Pending user',
      role: 'student',
      status: 'pending',
      email_verified: false,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: null,
      class: null,
      major: null,
      year: null,
      gpa: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    // Suspended user
    {
      id: '00000000-0000-0000-0000-000000000012',
      email: 'suspended@example.com',
      username: 'suspended',
      password: await hashUtils.password.hashPassword('Suspended123!'),
      first_name: 'Suspended',
      last_name: 'User',
      bio: 'Suspended user',
      role: 'student',
      status: 'suspended',
      email_verified: true,
      two_factor_enabled: false,
      token_version: 0,
      instructor_id: null,
      department: null,
      specialization: null,
      experience_years: null,
      education_level: null,
      student_id: null,
      class: null,
      major: null,
      year: null,
      gpa: null,
      created_at: new Date(),
      updated_at: new Date()
    }
  ];

  // Insert users
  for (const user of users) {
    // Check if user already exists
    const existingUser = await sequelize.query(
      'SELECT id FROM users WHERE id = ? OR email = ? OR username = ?',
      {
        replacements: [user.id, user.email, user.username],
        type: QueryTypes.SELECT
      }
    );

    if (existingUser.length > 0) {
      console.log(`User ${user.username} already exists, skipping...`);
      continue;
    }

    await sequelize.query(
      `INSERT INTO users (
        id, email, username, password, first_name, last_name, bio, role, status,
        email_verified, token_version, instructor_id, department, specialization, 
        experience_years, education_level, student_id, class, major, year, gpa, 
        created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      {
        replacements: [
          user.id, user.email, user.username, user.password, user.first_name,
          user.last_name, user.bio, user.role, user.status, user.email_verified,
          user.token_version || 0, user.instructor_id, user.department, user.specialization,
          user.experience_years, user.education_level, user.student_id, 
          user.class, user.major, user.year, user.gpa,
          user.created_at, user.updated_at
        ]
      }
    );
  }
}
